spring:
  data:
    cassandra:
      port: 9042
      contact-points: mycassandra
      keyspace-name: pizzastore
      entity-base-package: com.example.pizzabackend.pizzabackend.models
    mongodb:
      authentication-database: admin
      uri: mongodb+srv://mongo:mongo@cluster0.wl0dc.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      database: pizzastore
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <YOUR_CLIENT_ID>
            clientSecret: <YOUR_SECERET>
            scope:
              - email
              - profile